### PR TITLE
Add questions and answers

### PR DESCRIPTION
**Pull request by sibinx7**
@coderhs @manusajith 
I have added questions and answer. Please review it.

### CODE REVIEW

**Comment by coderhs** [comment]
@manusajith are you fine with this format? I was thinking he should have those answers in the master slide itself.

**Comment by manusajith** [comment]
A slide for FAQ as the second last slide is a good option, this is optional.

But the main points should definitely go into the master slides itself.

**Comment by coderhs** [comment]
@sibinx7 why is the branch called `web-seo` ? I don't think this commit have anything to do with SEO, its more about answers to our questions.

**Comment by sibinx7** [comment]
This  is the main branch to merge with master branch, Once users send pull request and i merged it with web seo, then correct images resolutions, check links, also change file name if it not correct.

**Comment by manusajith** [comment]
I think we can keep a few guidelines for the images and file names(I think this is already there) in the readme file and ask @redpanthers/devs  to follow that so that it will reduce your overhead.

**Pull request merged**
