### PR TITLE
Changed the heading 'Sample Markdown' slide to 'Markdown slide'

### PR DESCRIPTION
**Pull request by juliatjoy**

### CODE REVIEW

**Comment by manusajith** [comment]
@juliatjoy I see too many changed here. Can you pls check this PR once again ?

**Comment by juliatjoy** [comment]
@manusajith It's because I added all files for committing. The only change is the heading, others changes are file mode changes.

**Comment by manusajith** [comment]
@juliatjoy can you pls fix that, and only commit the changes that's necessary.

**Comment by manusajith** [comment]
@juliatjoy Two sections in the Readme are almost similar, so can we merge those 2 sections or tweak the content.

Referring to [this](https://github.com/redpanthers/slides/blob/docs-create_readme/Readme.md#creating-slide) and [this](https://github.com/redpanthers/slides/blob/docs-create_readme/Readme.md#instruction-to-add-new-slides-to-red-panthers)

**Comment by manusajith** [comment]
@sibinx7 I have updated Readme file, as well as update the site's desciption on config file.
Please review and merge. 

cc/ @juliatjoy

**Pull request merged**
